apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-svc-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      type: frontend
  #strategy:
  #  type: Roll
  replicas: 6
